=== zi-yu/orionsbelt/tests/conf/resources/conf.dtd
<!ELEMENT resources (resource*) >

<!ELEMENT resource (dependencies?, cost?, attributes?, onturn?, oncomplete?, onavailable?,onremove?,onCancelDuringBuild?,battle?,keywords?) >
<!ATTLIST resource type CDATA #REQUIRED>
<!ATTLIST resource value CDATA #REQUIRED>
<!ATTLIST resource always-create (true|false) #IMPLIED>
<!ATTLIST resource category (general|upgrade|planet|tech|exploration|fleet|soldier) #IMPLIED>
<!ATTLIST resource appliesTo (ruler|planet) "planet">

<!ELEMENT dependencies (resource-ref*,terrain?,battlesFought?,static?) >

	<!ELEMENT resource-ref EMPTY>
	<!ATTLIST resource-ref type CDATA #REQUIRED>
	<!ATTLIST resource-ref value CDATA #REQUIRED>

	<!ELEMENT battlesFought EMPTY>
	<!ATTLIST battlesFought value CDATA #REQUIRED>
	
	<!ELEMENT terrain EMPTY>
	<!ATTLIST terrain type CDATA #REQUIRED>

<!ELEMENT cost (housingAvailable*,resource-needed*,reserve-resource*,resource-available*,restriction*,queueRestriction*,disallow-build*,resource-ref*,duration?) >
<!ATTLIST cost allowUndoDuringBuild (true|false) "false">

	<!ELEMENT housingAvailable EMPTY>

	<!ELEMENT resource-needed EMPTY>
	<!ATTLIST resource-needed type CDATA #REQUIRED>
	<!ATTLIST resource-needed value CDATA #REQUIRED>
	
	<!ELEMENT reserve-resource EMPTY>
	<!ATTLIST reserve-resource type CDATA #REQUIRED>
	<!ATTLIST reserve-resource value CDATA #REQUIRED>
	
	<!ELEMENT resource-available EMPTY>
	<!ATTLIST resource-available type CDATA "Intrinsic">
	<!ATTLIST resource-available resource CDATA #REQUIRED>
	<!ATTLIST resource-available value CDATA "1">

	<!ELEMENT duration EMPTY>
	<!ATTLIST duration value CDATA #REQUIRED>
	<!ATTLIST duration quantity CDATA "1">
	<!ATTLIST duration dependency CDATA #IMPLIED>
	<!ATTLIST duration function CDATA #IMPLIED>

	<!ELEMENT disallow-build EMPTY>
	<!ATTLIST disallow-build category CDATA #REQUIRED>
	<!ATTLIST disallow-build factory CDATA #REQUIRED>
	
	<!ELEMENT restriction EMPTY>
	<!ATTLIST restriction resource CDATA #REQUIRED>
	<!ATTLIST restriction type (less-than|bigger-than|equal-to) #REQUIRED>
	<!ATTLIST restriction value CDATA #REQUIRED>

	<!ELEMENT queueRestriction EMPTY>
	<!ATTLIST queueRestriction type CDATA #REQUIRED>
	<!ATTLIST queueRestriction value CDATA #REQUIRED>
	
<!ELEMENT attributes (attribute*,mod*)>

	<!ELEMENT attribute EMPTY>
	<!ATTLIST attribute type CDATA #REQUIRED>
	<!ATTLIST attribute value CDATA #REQUIRED>
	<!ATTLIST attribute group (true|false) "false">

	<!ELEMENT mod EMPTY>
	<!ATTLIST mod type CDATA #REQUIRED>
	<!ATTLIST mod value CDATA #REQUIRED>
	<!ATTLIST mod apply-once (true|false) #IMPLIED>
	
<!ELEMENT onturn (transform*,transformRareResource*)>

	<!ELEMENT transformRareResource EMPTY>
	<!ATTLIST transformRareResource rare CDATA #REQUIRED>
	<!ATTLIST transformRareResource intrinsic CDATA #REQUIRED>
	<!ATTLIST transformRareResource factor CDATA #REQUIRED>

	<!ELEMENT transform EMPTY>
	<!ATTLIST transform input CDATA #REQUIRED>
	<!ATTLIST transform output CDATA #REQUIRED>
	<!ATTLIST transform factor CDATA #REQUIRED>

<!ELEMENT oncomplete (addRatio*,supress-factory*,add*)>

	<!ELEMENT supress-factory EMPTY>
	<!ATTLIST supress-factory type CDATA #REQUIRED>
	<!ATTLIST supress-factory value CDATA #REQUIRED>

	<!ELEMENT addRatio EMPTY>
	<!ATTLIST addRatio type CDATA #REQUIRED>
	<!ATTLIST addRatio value CDATA #REQUIRED>
	
<!ELEMENT onavailable (add*)>

	<!ELEMENT add EMPTY>
	<!ATTLIST add type CDATA #REQUIRED>
	<!ATTLIST add resource CDATA #REQUIRED>
	<!ATTLIST add value CDATA #REQUIRED>
	
<!ELEMENT onremove (static*,add*)>

	<!ELEMENT static EMPTY>
	<!ATTLIST static evaluate (true|false) #REQUIRED>
	<!ATTLIST static action (true|false) #REQUIRED>

<!ELEMENT onCancelDuringBuild (static*,add*)>

<!ELEMENT keywords (keyword*)>

<!ELEMENT keyword EMPTY>
	<!ATTLIST keyword key CDATA #REQUIRED>

<!ELEMENT battle (attack,defense,movement)>
	<!ATTLIST battle unitType (light|medium|heavy|animal|special|building) #REQUIRED>

<!ELEMENT target EMPTY>
	<!ATTLIST target type (unit|terrain|level) #REQUIRED>
	<!ATTLIST target key CDATA #REQUIRED>
	<!ATTLIST target value CDATA #REQUIRED>

<!ELEMENT attack (target*,terrain*)>
	<!ATTLIST attack base CDATA #REQUIRED>
	<!ATTLIST attack range CDATA #REQUIRED>
	<!ATTLIST attack maximumDamage CDATA #REQUIRED>
	<!ATTLIST attack minimumDamage CDATA #REQUIRED>
	<!ATTLIST attack canDamageBehindUnits (true|false) "false">
	<!ATTLIST attack catapultAttack (true|false) "false">
	<!ATTLIST attack replicatorAttack (true|false) "false">
	<!ATTLIST attack tripleAttack (true|false) "false">
	
<!ELEMENT defense (target*,terrain*)>
	<!ATTLIST defense base CDATA #REQUIRED>
	<!ATTLIST defense hitPoints CDATA #REQUIRED>
	<!ATTLIST defense canStrikeBack (true|false) "false">
	
<!ELEMENT movement EMPTY>
	<!ATTLIST movement cost CDATA #REQUIRED>
	<!ATTLIST movement type CDATA #REQUIRED>
	<!ATTLIST movement level (air|ground) #REQUIRED>

=== zi-yu/orionsbelt/rules/resources/waterresourcegenerator.xml
<?xml version="1.0" ?>
<!DOCTYPE resources SYSTEM "conf.dtd">
<resources>

	<resource type="Building" value="WaterPower" category="general">
		<dependencies>
			<resource-ref type="Research" value="WaterExplorationI" />
		</dependencies>
		<cost>
			<resource-needed type="mp" value="700" />
			<resource-needed type="waterSpace" value="1" />
			<resource-available type="Intrinsic" resource="labor" value="800" />
			<duration value="7"/>
		</cost>
		<attributes>
			<mod type="energy" value="100"/>
			<mod type="culture" value="-1"/>
			<mod type="polution" value="10"/>
		</attributes>
		<oncomplete>
			<add type="Intrinsic" resource="score" value="1" />
		</oncomplete>
		<onavailable>
			<add type="Intrinsic" resource="energy" value="500" />
		</onavailable>
		<onremove>
			<add type="Intrinsic" resource="mp" value="200" />
			<add type="Intrinsic" resource="waterSpace" value="1" />
			<add type="Intrinsic" resource="score" value="-1" />
		</onremove>
		<onCancelDuringBuild>
			<add type="Intrinsic" resource="waterSpace" value="1" />
		</onCancelDuringBuild>
		<keywords>
			<keyword key="waterSpace" />
			<keyword key="energy" />
			<keyword key="resourceGenerator" />
		</keywords>
	</resource>
	
	<resource type="Building" value="FishingFacility" category="general">
		<dependencies>
			<resource-ref type="Research" value="WaterExplorationI" />
		</dependencies>
		<cost>
			<resource-needed type="mp" value="400" />
			<resource-needed type="gold" value="600" />
			<resource-needed type="waterSpace" value="1" />
			<resource-available type="Intrinsic" resource="labor" value="1000" />
			<duration value="6"/>
		</cost>
		<attributes>
			<mod type="energy" value="-20" />
			<mod type="food" value="4500"/>
			<mod type="culture" value="-2" />
		</attributes>
		<oncomplete>
			<add type="Intrinsic" resource="score" value="1" />
		</oncomplete>
		<onavailable>
			<add type="Intrinsic" resource="food" value="600" />
		</onavailable>
		<onremove>
			<add type="Intrinsic" resource="mp" value="200" />
			<add type="Intrinsic" resource="waterSpace" value="1" />
			<add type="Intrinsic" resource="score" value="-1" />
		</onremove>
		<onCancelDuringBuild>
			<add type="Intrinsic" resource="waterSpace" value="1" />
		</onCancelDuringBuild>
		<keywords>
			<keyword key="waterSpace" />
			<keyword key="food" />
			<keyword key="resourceGenerator" />
		</keywords>
	</resource>

	<resource type="Building" value="WaterHouse" category="general">
		<dependencies>
			<resource-ref type="Research" value="WaterExplorationI" />
		</dependencies>
		<cost>
			<resource-needed type="mp" value="900" />
			<resource-needed type="waterSpace" value="1" />
			<resource-available type="Intrinsic" resource="labor" value="1000" />
			<duration value="6"/>
		</cost>
		<attributes>
			<mod type="energy" value="-15" />
			<mod type="labor" value="150" />
		</attributes>
		<oncomplete>
			<add type="Intrinsic" resource="housing" value="2000" />
			<add type="Intrinsic" resource="score" value="1" />
		</oncomplete>
		<onremove>
			<add type="Intrinsic" resource="mp" value="200" />
			<add type="Intrinsic" resource="housing" value="-2000" />
			<add type="Intrinsic" resource="waterSpace" value="1" />
			<add type="Intrinsic" resource="score" value="-1" />
		</onremove>
		<onCancelDuringBuild>
			<add type="Intrinsic" resource="waterSpace" value="1" />
		</onCancelDuringBuild>
		<keywords>
			<keyword key="waterSpace" />
			<keyword key="labor" />
			<keyword key="housing" />
			<keyword key="resourceGenerator" />
		</keywords>
	</resource>
	
	<resource type="Building" value="Etar" category="general">
		<dependencies>
			<resource-ref type="Research" value="Recycling" />
			<resource-ref type="Research" value="WaterExplorationI" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="1800" />
			<resource-needed type="mp" value="1000" />
			<resource-needed type="waterSpace" value="1" />
			<resource-available type="Intrinsic" resource="labor" value="1600" />
			<duration value="20"/>
		</cost>
		<attributes>
			<mod type="energy" value="-150"/>
			<mod type="polution" value="-250"/>
		</attributes>
		<oncomplete>
			<add type="Intrinsic" resource="score" value="50" />
		</oncomplete>
		<onavailable/>
		<onremove>
			<add type="Intrinsic" resource="waterSpace" value="1" />
			<add type="Intrinsic" resource="score" value="-50" />
		</onremove>
		<onCancelDuringBuild>
			<add type="Intrinsic" resource="waterSpace" value="1" />
		</onCancelDuringBuild>
		<keywords>
			<keyword key="waterSpace" />
			<keyword key="resourceGenerator" />
			<keyword key="polution" />
		</keywords>
	</resource>

	<resource type="Building" value="WaterMine" category="general">
		<dependencies>
			<resource-ref type="Research" value="WaterExplorationI" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="1000" />
			<resource-needed type="mp" value="1100" />
			<resource-needed type="waterSpace" value="1" />
			<resource-available type="Intrinsic" resource="labor" value="1000" />
			<duration value="20"/>
		</cost>
		<attributes>
			<mod type="energy" value="-30" />
			<mod type="mp" value="100"/>
			<mod type="culture" value="-6" />
			<mod type="polution" value="30" />
		</attributes>
		<oncomplete>
			<add type="Intrinsic" resource="score" value="2" />
		</oncomplete>
		<onavailable/>
		<onremove>
			<add type="Intrinsic" resource="waterSpace" value="1" />
			<add type="Intrinsic" resource="score" value="-2" />
		</onremove>
		<onCancelDuringBuild>
			<add type="Intrinsic" resource="waterSpace" value="1" />
		</onCancelDuringBuild>
		<keywords>
			<keyword key="waterSpace" />
			<keyword key="resourceGenerator" />
			<keyword key="polution" />
		</keywords>
	</resource>


</resources>

=== zi-yu/orionsbelt/chronos/conf/resources/tanks.xml
<?xml version="1.0" ?>
<!DOCTYPE resources SYSTEM "conf.dtd">
<resources>

	<resource type="Tank" value="Bozer">
		<dependencies>
			<resource-ref type="Building" value="TankFacility" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="200" />
			<resource-needed type="mp" value="300" />
			<resource-needed type="energy" value="150" />
			<resource-ref type="Building" value="TankFacility" />
			<duration value="10" quantity="100" />
		</cost>
		<attributes>
			<attribute type="TeletransportationCost" value="350"/>
		</attributes>
		<oncomplete/>
		<battle>			<attack base="300" range="6" maximumDamage="9" minimumDamage="5">				<target type="unit" key="animal" value="50" />				<target type="terrain" key="ice" value="-50" />				<target type="terrain" key="rock" value="50" />
				<target type="terrain" key="desert" value="50" />
				<target type="level" key="air" value="50" />			</attack>			<defense base="300" hitPoints="10" canStrikeBack="true">
				<target type="unit" key="animal" value="20" />				<target type="terrain" key="desert" value="-50" />
				<target type="level" key="air" value="-100" />				<target type="terrain" key="forest" value="150" />			</defense>
			<movement cost="2" type="normal" level="ground" />		</battle>
	</resource>
	
</resources>

=== zi-yu/orionsbelt/chronos/conf/resources/intrinsic.xml
<?xml version="1.0" ?>
<!DOCTYPE resources SYSTEM "conf.dtd">
<resources>
	<!-- planetas -->
	<resource type="Intrinsic" value="gold">
		<attributes>
			<attribute type="DefaultRatio" value="50"/>
			<attribute type="Teletransportable" value="1"/>
			<attribute type="TeletransportationCost" value="2"/>
		</attributes>
	</resource>
	
	<resource type="Intrinsic" value="labor">
		<cost>
			<housingAvailable />
		</cost>
		<attributes>
			<attribute type="DefaultRatio" value="20"/>
			<attribute type="Teletransportable" value="1"/>
			<attribute type="TeletransportationCost" value="3"/>
			<mod type="food" value="-1" />
		</attributes>
	</resource>
	
	<resource type="Intrinsic" value="mp">
		<attributes>
			<attribute type="DefaultRatio" value="50"/>
			<attribute type="MarketResource" value="1"/>
			<attribute type="Teletransportable" value="1"/>
			<attribute type="TeletransportationCost" value="2"/>
		</attributes>
	</resource>
	
	<resource type="Intrinsic" value="culture">
		<attributes>
			<attribute type="DefaultRatio" value="100"/>
		</attributes>
	</resource>
	
	<resource type="Intrinsic" value="energy">
		<attributes>
			<attribute type="DefaultRatio" value="50"/>
			<attribute type="MarketResource" value="1"/>
			<attribute type="TeletransportationCost" value="2"/>
		</attributes>
	</resource>
	
	<resource type="Intrinsic" value="polution">
		<attributes>
			<attribute type="DefaultRatio" value="20"/>
		</attributes>
	</resource>
	
	<resource type="Intrinsic" value="housing">
		<attributes>
			<attribute type="DefaultRatio" value="0"/>
		</attributes>
	</resource>
	
	<resource type="Intrinsic" value="food">
		<attributes>
			<attribute type="DefaultRatio" value="50"/>
			<attribute type="MarketResource" value="1"/>
			<attribute type="Teletransportable" value="1"/>
			<attribute type="TeletransportationCost" value="1"/>
		</attributes>
	</resource>

	<resource type="Intrinsic" value="score">
		<attributes>
			<attribute type="DefaultRatio" value="100"/>
		</attributes>
	</resource>
	
	<resource type="Intrinsic" value="groundSpace">
		<attributes>
			<attribute type="DefaultValue" value="20"/>
		</attributes>
	</resource>

	<resource type="Intrinsic" value="orbitSpace">
		<attributes>
			<attribute type="DefaultValue" value="30"/>
		</attributes>
	</resource>

	<resource type="Intrinsic" value="waterSpace">
		<attributes>
			<attribute type="DefaultValue" value="30"/>
		</attributes>
	</resource>

	
	<!-- Rulers -->
	<resource type="Intrinsic" value="score" appliesTo="ruler">
		</resource>
	
	<resource type="Intrinsic" value="culture" appliesTo="ruler">
		</resource>
	
	<resource type="Intrinsic" value="maxPlanets" appliesTo="ruler">
		<onavailable>
			<add type="Intrinsic" resource="maxPlanets" value="2" />
		</onavailable>
	</resource>

	<resource type="Intrinsic" value="maxFleets" appliesTo="ruler" />
	
	<resource type="Intrinsic" value="queueCapacity" appliesTo="ruler">
		<onavailable>
			<add type="Intrinsic" resource="queueCapacity" value="2" />
		</onavailable>
	</resource>

	<resource type="Intrinsic" value="scanCost" appliesTo="ruler">
		<onavailable>
			<add type="Intrinsic" resource="scanCost" value="100" />
		</onavailable>
	</resource>
	
</resources>

=== zi-yu/orionsbelt/alnitak/configuration/resources/rarebuildings.xml
<?xml version="1.0" ?>
<!DOCTYPE resources SYSTEM "conf.dtd">
<resources>
	
	<!-- EdifÃ­cios que tratam recursos raros -->
	<resource type="Building" value="ElkFacility" category="general">
		<dependencies>
			<resource-ref type="Research" value="RareResources" />
			<resource-ref type="Research" value="Commerce" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="3000" />
			<resource-needed type="mp" value="400" />
			<resource-needed type="energy" value="5700" />
			<resource-needed type="groundSpace" value="1" />
			<resource-available type="Intrinsic" resource="labor" value="2500" />
			<duration value="60"/>
		</cost>
		<onturn>
			<transformRareResource rare="elk" intrinsic="food" factor="9000" />
		</onturn>
		<oncomplete>
			<add type="Intrinsic" resource="score" value="350" />
		</oncomplete>
		<onremove>
			<add type="Intrinsic" resource="groundSpace" value="1" />
			<add type="Intrinsic" resource="score" value="-350" />
		</onremove>
		<onCancelDuringBuild>
			<add type="Intrinsic" resource="groundSpace" value="1" />
		</onCancelDuringBuild>
		<keywords>
			<keyword key="groundSpace" />
			<keyword key="food" />
			<keyword key="RareResources" />
		</keywords>
	</resource>
	
	<resource type="Building" value="HidroPlant" category="general">
		<dependencies>
			<resource-ref type="Research" value="RareResources" />
			<resource-ref type="Research" value="Commerce" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="1500" />
			<resource-needed type="mp" value="1400" />
			<resource-needed type="energy" value="1700" />
			<resource-needed type="waterSpace" value="1" />
			<resource-available type="Intrinsic" resource="labor" value="2000" />
			<duration value="70"/>
		</cost>
		<attributes>
			<mod type="polution" value="100"/>
		</attributes>
		<onturn>
			<transformRareResource rare="hydrogen" intrinsic="energy" factor="1000" />
		</onturn>
		<oncomplete>
			<add type="Intrinsic" resource="score" value="300" />
		</oncomplete>
		<onremove>
			<add type="Intrinsic" resource="waterSpace" value="1" />
			<add type="Intrinsic" resource="score" value="-300" />
		</onremove>
		<onCancelDuringBuild>
			<add type="Intrinsic" resource="waterSpace" value="1" />
		</onCancelDuringBuild>
		<keywords>
			<keyword key="waterSpace" />
			<keyword key="energy" />
			<keyword key="RareResources" />
		</keywords>
	</resource>
	
	<resource type="Building" value="OilPlant" category="general">
		<dependencies>
			<resource-ref type="Research" value="RareResources" />
			<resource-ref type="Research" value="WaterExplorationI" />
			<resource-ref type="Research" value="Geology" />
			<resource-ref type="Building" value="WaterUniversity" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="4400" />
			<resource-needed type="mp" value="4800" />
			<resource-needed type="waterSpace" value="1" />
			<resource-available type="Intrinsic" resource="labor" value="2600" />
			<duration value="90"/>
		</cost>
		<attributes>
			<mod type="polution" value="150"/>
			<mod type="energy" value="-150"/>
		</attributes>
		<onturn>
			<transformRareResource rare="oil" intrinsic="mp" factor="800" />
		</onturn>
		<oncomplete>
			<add type="Intrinsic" resource="score" value="300" />
		</oncomplete>
		<onavailable/>
		<onremove>
			<add type="Intrinsic" resource="waterSpace" value="1" />
			<add type="Intrinsic" resource="score" value="-300" />
		</onremove>
		<onCancelDuringBuild>
			<add type="Intrinsic" resource="waterSpace" value="1" />
		</onCancelDuringBuild>
		<keywords>
			<keyword key="waterSpace" />
			<keyword key="resourceGenerator" />
			<keyword key="RareResources" />
		</keywords>
	</resource>
	
	<resource type="Building" value="DiamondShop" category="general">
		<dependencies>
			<resource-ref type="Research" value="RareResources" />
			<resource-ref type="Research" value="Commerce" />
			<resource-ref type="Building" value="University" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="4000" />
			<resource-needed type="mp" value="5000" />
			<resource-needed type="groundSpace" value="1" />
			<resource-available type="Intrinsic" resource="labor" value="3600" />
			<duration value="90"/>
		</cost>
		<attributes>
			<mod type="polution" value="150"/>
			<mod type="energy" value="-150"/>
		</attributes>
		<onturn>
			<transformRareResource rare="diamond" intrinsic="gold" factor="1000" />
		</onturn>
		<oncomplete>
			<add type="Intrinsic" resource="score" value="300" />
		</oncomplete>
		<onavailable/>
		<onremove>
			<add type="Intrinsic" resource="groundSpace" value="1" />
			<add type="Intrinsic" resource="score" value="-300" />
		</onremove>
		<onCancelDuringBuild>
			<add type="Intrinsic" resource="groundSpace" value="1" />
		</onCancelDuringBuild>
		<keywords>
			<keyword key="groundSpace" />
			<keyword key="resourceGenerator" />
			<keyword key="RareResources" />
		</keywords>
	</resource>
	
	<resource type="Building" value="SilverShop" category="general">
		<dependencies>
			<resource-ref type="Research" value="RareResources" />
			<resource-ref type="Research" value="Commerce" />
			<resource-ref type="Building" value="University" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="5000" />
			<resource-needed type="mp" value="4000" />
			<resource-needed type="waterSpace" value="1" />
			<resource-available type="Intrinsic" resource="labor" value="3000" />
			<duration value="85"/>
		</cost>
		<attributes>
			<mod type="polution" value="150"/>
			<mod type="energy" value="-150"/>
		</attributes>
		<onturn>
			<transformRareResource rare="silver" intrinsic="gold" factor="1000" />
		</onturn>
		<oncomplete>
			<add type="Intrinsic" resource="score" value="300" />
		</oncomplete>
		<onavailable/>
		<onremove>
			<add type="Intrinsic" resource="waterSpace" value="1" />
			<add type="Intrinsic" resource="score" value="-300" />
		</onremove>
		<onCancelDuringBuild>
			<add type="Intrinsic" resource="waterSpace" value="1" />
		</onCancelDuringBuild>
		<keywords>
			<keyword key="waterSpace" />
			<keyword key="resourceGenerator" />
			<keyword key="RareResources" />
		</keywords>
	</resource>
	
	<resource type="Building" value="GasPlant" category="general">
		<dependencies>
			<resource-ref type="Research" value="RareResources" />
			<resource-ref type="Research" value="Geology" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="3500" />
			<resource-needed type="mp" value="2400" />
			<resource-needed type="energy" value="3700" />
			<resource-needed type="groundSpace" value="1" />
			<resource-available type="Intrinsic" resource="labor" value="2000" />
			<duration value="65"/>
		</cost>
		<attributes>
			<mod type="polution" value="100"/>
		</attributes>
		<onturn>
			<transformRareResource rare="gas" intrinsic="energy" factor="1200" />
		</onturn>
		<oncomplete>
			<add type="Intrinsic" resource="score" value="300" />
		</oncomplete>
		<onremove>
			<add type="Intrinsic" resource="groundSpace" value="1" />
			<add type="Intrinsic" resource="score" value="-300" />
		</onremove>
		<onCancelDuringBuild>
			<add type="Intrinsic" resource="groundSpace" value="1" />
		</onCancelDuringBuild>
		<keywords>
			<keyword key="groundSpace" />
			<keyword key="energy" />
			<keyword key="RareResources" />
		</keywords>
	</resource>
	
</resources>
