=== zi-yu/orionsbelt/tests/conf/resources/conf.dtd
<!ELEMENT resources (resource*) >

<!ELEMENT resource (dependencies?, cost?, attributes?, onturn?, oncomplete?, onavailable?,onremove?,onCancelDuringBuild?,battle?,keywords?) >
<!ATTLIST resource type CDATA #REQUIRED>
<!ATTLIST resource value CDATA #REQUIRED>
<!ATTLIST resource always-create (true|false) #IMPLIED>
<!ATTLIST resource category (general|upgrade|planet|tech|exploration|fleet|soldier) #IMPLIED>
<!ATTLIST resource appliesTo (ruler|planet) "planet">

<!ELEMENT dependencies (resource-ref*,terrain?,battlesFought?,static?) >

	<!ELEMENT resource-ref EMPTY>
	<!ATTLIST resource-ref type CDATA #REQUIRED>
	<!ATTLIST resource-ref value CDATA #REQUIRED>

	<!ELEMENT battlesFought EMPTY>
	<!ATTLIST battlesFought value CDATA #REQUIRED>
	
	<!ELEMENT terrain EMPTY>
	<!ATTLIST terrain type CDATA #REQUIRED>

<!ELEMENT cost (housingAvailable*,resource-needed*,reserve-resource*,resource-available*,restriction*,queueRestriction*,disallow-build*,resource-ref*,duration?) >
<!ATTLIST cost allowUndoDuringBuild (true|false) "false">

	<!ELEMENT housingAvailable EMPTY>

	<!ELEMENT resource-needed EMPTY>
	<!ATTLIST resource-needed type CDATA #REQUIRED>
	<!ATTLIST resource-needed value CDATA #REQUIRED>
	
	<!ELEMENT reserve-resource EMPTY>
	<!ATTLIST reserve-resource type CDATA #REQUIRED>
	<!ATTLIST reserve-resource value CDATA #REQUIRED>
	
	<!ELEMENT resource-available EMPTY>
	<!ATTLIST resource-available type CDATA "Intrinsic">
	<!ATTLIST resource-available resource CDATA #REQUIRED>
	<!ATTLIST resource-available value CDATA "1">

	<!ELEMENT duration EMPTY>
	<!ATTLIST duration value CDATA #REQUIRED>
	<!ATTLIST duration quantity CDATA "1">
	<!ATTLIST duration dependency CDATA #IMPLIED>
	<!ATTLIST duration function CDATA #IMPLIED>

	<!ELEMENT disallow-build EMPTY>
	<!ATTLIST disallow-build category CDATA #REQUIRED>
	<!ATTLIST disallow-build factory CDATA #REQUIRED>
	
	<!ELEMENT restriction EMPTY>
	<!ATTLIST restriction resource CDATA #REQUIRED>
	<!ATTLIST restriction type (less-than|bigger-than|equal-to) #REQUIRED>
	<!ATTLIST restriction value CDATA #REQUIRED>

	<!ELEMENT queueRestriction EMPTY>
	<!ATTLIST queueRestriction type CDATA #REQUIRED>
	<!ATTLIST queueRestriction value CDATA #REQUIRED>
	
<!ELEMENT attributes (attribute*,mod*)>

	<!ELEMENT attribute EMPTY>
	<!ATTLIST attribute type CDATA #REQUIRED>
	<!ATTLIST attribute value CDATA #REQUIRED>
	<!ATTLIST attribute group (true|false) "false">

	<!ELEMENT mod EMPTY>
	<!ATTLIST mod type CDATA #REQUIRED>
	<!ATTLIST mod value CDATA #REQUIRED>
	<!ATTLIST mod apply-once (true|false) #IMPLIED>
	
<!ELEMENT onturn (transform*,transformRareResource*)>

	<!ELEMENT transformRareResource EMPTY>
	<!ATTLIST transformRareResource rare CDATA #REQUIRED>
	<!ATTLIST transformRareResource intrinsic CDATA #REQUIRED>
	<!ATTLIST transformRareResource factor CDATA #REQUIRED>

	<!ELEMENT transform EMPTY>
	<!ATTLIST transform input CDATA #REQUIRED>
	<!ATTLIST transform output CDATA #REQUIRED>
	<!ATTLIST transform factor CDATA #REQUIRED>

<!ELEMENT oncomplete (addRatio*,supress-factory*,add*)>

	<!ELEMENT supress-factory EMPTY>
	<!ATTLIST supress-factory type CDATA #REQUIRED>
	<!ATTLIST supress-factory value CDATA #REQUIRED>

	<!ELEMENT addRatio EMPTY>
	<!ATTLIST addRatio type CDATA #REQUIRED>
	<!ATTLIST addRatio value CDATA #REQUIRED>
	
<!ELEMENT onavailable (add*)>

	<!ELEMENT add EMPTY>
	<!ATTLIST add type CDATA #REQUIRED>
	<!ATTLIST add resource CDATA #REQUIRED>
	<!ATTLIST add value CDATA #REQUIRED>
	
<!ELEMENT onremove (static*,add*)>

	<!ELEMENT static EMPTY>
	<!ATTLIST static evaluate (true|false) #REQUIRED>
	<!ATTLIST static action (true|false) #REQUIRED>

<!ELEMENT onCancelDuringBuild (static*,add*)>

<!ELEMENT keywords (keyword*)>

<!ELEMENT keyword EMPTY>
	<!ATTLIST keyword key CDATA #REQUIRED>

<!ELEMENT battle (attack,defense,movement)>
	<!ATTLIST battle unitType (light|medium|heavy|animal|special|building) #REQUIRED>

<!ELEMENT target EMPTY>
	<!ATTLIST target type (unit|terrain|level) #REQUIRED>
	<!ATTLIST target key CDATA #REQUIRED>
	<!ATTLIST target value CDATA #REQUIRED>

<!ELEMENT attack (target*,terrain*)>
	<!ATTLIST attack base CDATA #REQUIRED>
	<!ATTLIST attack range CDATA #REQUIRED>
	<!ATTLIST attack maximumDamage CDATA #REQUIRED>
	<!ATTLIST attack minimumDamage CDATA #REQUIRED>
	<!ATTLIST attack canDamageBehindUnits (true|false) "false">
	<!ATTLIST attack catapultAttack (true|false) "false">
	<!ATTLIST attack replicatorAttack (true|false) "false">
	<!ATTLIST attack tripleAttack (true|false) "false">
	
<!ELEMENT defense (target*,terrain*)>
	<!ATTLIST defense base CDATA #REQUIRED>
	<!ATTLIST defense hitPoints CDATA #REQUIRED>
	<!ATTLIST defense canStrikeBack (true|false) "false">
	
<!ELEMENT movement EMPTY>
	<!ATTLIST movement cost CDATA #REQUIRED>
	<!ATTLIST movement type CDATA #REQUIRED>
	<!ATTLIST movement level (air|ground) #REQUIRED>

=== zi-yu/orionsbelt/chronos/conf/resources/ships.xml
<?xml version="1.0" ?>
<!DOCTYPE resources SYSTEM "conf.dtd">
<resources>

	<resource type="Ship" value="ColonyShip">
		<dependencies>
			<resource-ref type="Building" value="StarPort" />
			<resource-ref type="Research" value="AdvancedFlightI" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="5000" />
			<resource-needed type="mp" value="8000" />
			<resource-needed type="energy" value="1000" />
			<resource-ref type="Building" value="StarPort" />
			<duration value="15" quantity="1" />
		</cost>
		<attributes>
			<attribute type="TeletransportationCost" value="350"/>
		</attributes>
		<oncomplete/>
		<battle>			<attack base="50" range="6" maximumDamage="9" minimumDamage="5">				<target type="unit" key="animal" value="20" />				<target type="terrain" key="ice" value="-30" />				<target type="terrain" key="rock" value="30" />
				<target type="level" key="air" value="50" />			</attack>			<defense base="10" hitPoints="10" canStrikeBack="true">
				<target type="unit" key="animal" value="20" />				<target type="terrain" key="desert" value="30" />
				<target type="level" key="ground" value="500" />			</defense>
			<movement cost="1" type="front" level="air" />		</battle>
	</resource>

	<resource type="Ship" value="LightShip">
		<dependencies>
			<resource-ref type="Building" value="StarPort" />
			<resource-ref type="Research" value="AdvancedFlightI" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="100" />
			<resource-needed type="mp" value="140" />
			<resource-needed type="energy" value="40" />
			<resource-ref type="Building" value="StarPort" />
			<duration value="4" quantity="100" />
		</cost>
		<attributes>
			<attribute type="TeletransportationCost" value="1" />
		</attributes>
		<oncomplete />
		<battle>
			<attack base="40" range="1" maximumDamage="9" minimumDamage="5">
				<target type="terrain" key="ice" value="-10" />
				<target type="terrain" key="rock" value="-10" />
			</attack>
			<defense base="50" hitPoints="10">
				<target type="unit" key="animal" value="30" />
				<target type="unit" key="tank" value="50" />
			</defense>

			<movement cost="1" type="all"  level="air"/>
		</battle>
	</resource>

	<resource type="Ship" value="HeavyShip">
		<dependencies>
			<resource-ref type="Building" value="StarPort" />
			<resource-ref type="Research" value="AdvancedFlightII" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="250" />
			<resource-needed type="mp" value="400" />
			<resource-needed type="energy" value="140" />
			<resource-ref type="Building" value="StarPort" />
			<duration value="10" quantity="100" />
		</cost>
		<attributes>
			<attribute type="TeletransportationCost" value="3" />
		</attributes>
		<battle>
			<attack base="570" range="3" maximumDamage="9" minimumDamage="5">
				<target type="unit" key="animal" value="200" />
				<target type="terrain" key="ice" value="-100" />
				<target type="terrain" key="rock" value="-100" />
			</attack>
			<defense base="580" hitPoints="10">
				<target type="unit" key="animal" value="100" />
				<target type="unit" key="tank" value="50" />
			</defense>

			<movement cost="3" type="normal" level="air" />
		</battle>
	</resource>

	<resource type="Ship" value="Crusader">
		<dependencies>
			<resource-ref type="Building" value="StarPort" />
			<resource-ref type="Research" value="AdvancedFlightIII" />
			<battlesFought value="5" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="2500" />
			<resource-needed type="mp" value="2500" />
			<resource-needed type="energy" value="1000" />
			<resource-ref type="Building" value="StarPort" />
			<duration value="40" quantity="100" />
		</cost>
		<attributes>
			<attribute type="TeletransportationCost" value="5" />
		</attributes>
		<battle>
			<attack base="2150" range="6" maximumDamage="9" minimumDamage="5">
				<target type="unit" key="animal" value="20" />
				<target type="terrain" key="ice" value="-200" />
				<target type="terrain" key="water" value="-200" />
				<target type="terrain" key="rock" value="150" />
			</attack>
			<defense base="1800" hitPoints="10">
				<target type="unit" key="animal" value="200" />
				<target type="unit" key="tank" value="-300" />
			</defense>
			<movement cost="4" type="front" level="air" />		</battle>
	</resource>

	<resource type="Ship" value="Pretorian">
		<dependencies>
			<resource-ref type="Building" value="StarPort" />
			<resource-ref type="Research" value="ShipShields" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="2000" />
			<resource-needed type="mp" value="2000" />
			<resource-needed type="energy" value="1400" />
			<resource-ref type="Building" value="StarPort" />
			<duration value="23" quantity="100" />
		</cost>
		<attributes>
			<attribute type="TeletransportationCost" value="4" />
		</attributes>
		<battle>
			<attack base="150" range="2" maximumDamage="9" minimumDamage="5">
				<target type="unit" key="animal" value="20" />
				<target type="terrain" key="ice" value="-30" />
				<target type="terrain" key="rock" value="30" />
			</attack>
			<defense base="2500" hitPoints="10">
				<target type="unit" key="animal" value="300" />
				<target type="terrain" key="desert" value="30" />
			</defense>

			<movement cost="2" type="diagonal" level="air" />		</battle>
	</resource>

	<resource type="Ship" value="Kamikaze">
		<dependencies>
			<resource-ref type="Building" value="StarPort" />
			<resource-ref type="Research" value="ShipFirePower" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="1000" />
			<resource-needed type="mp" value="1500" />
			<resource-needed type="energy" value="900" />
			<resource-ref type="Building" value="StarPort" />
			<duration value="35" quantity="100" />
		</cost>
		<attributes>
			<attribute type="TeletransportationCost" value="4"/>
		</attributes>
		<battle>			<attack base="3000" range="1" maximumDamage="9" minimumDamage="5">				<target type="unit" key="animal" value="20" />				<target type="terrain" key="ice" value="-30" />				<target type="terrain" key="rock" value="30" />			</attack>			<defense base="1" hitPoints="10">
				<target type="unit" key="animal" value="20" />				<target type="terrain" key="desert" value="30" />			</defense>
			<movement cost="2" type="all" level="air" />
		</battle>
	</resource>
	
	<resource type="Ship" value="Vector">
		<dependencies>
			<resource-ref type="Building" value="StarPort" />
			<resource-ref type="Research" value="ShipFirePower" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="2000" />
			<resource-needed type="mp" value="1800" />
			<resource-needed type="energy" value="1300" />
			<resource-ref type="Building" value="StarPort" />
			<duration value="30" quantity="100" />
		</cost>
		<attributes>
			<attribute type="TeletransportationCost" value="4"/>
		</attributes>
		<battle>			<attack base="2000" range="3" maximumDamage="9" minimumDamage="5">				<target type="unit" key="animal" value="200" />				<target type="terrain" key="ice" value="300" />				<target type="terrain" key="water" value="300" />				<target type="terrain" key="rock" value="300" />				<target type="unit" key="tank" value="100" />			</attack>			<defense base="1800" hitPoints="10">
				<target type="unit" key="animal" value="200" />				<target type="terrain" key="desert" value="-300" />				<target type="terrain" key="rock" value="-300" />				<target type="terrain" key="forest" value="-100" />			</defense>
			<movement cost="3" type="diagonal" level="air" />
		</battle>
	</resource>
	
	<resource type="Ship" value="NuclearBomber">
		<dependencies>
			<resource-ref type="Building" value="StarPort" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="1600" />
			<resource-needed type="mp" value="2700" />
			<resource-needed type="energy" value="1800" />
			<resource-needed type="uranium" value="2" />
			<resource-ref type="Building" value="StarPort" />
			<duration value="30" quantity="100" />
		</cost>
		<attributes>
			<attribute type="TeletransportationCost" value="4"/>
		</attributes>
		<battle>			<attack base="2200" range="4" maximumDamage="9" minimumDamage="5">				<target type="unit" key="animal" value="500" />				<target type="unit" key="ship" value="-200" />				<target type="unit" key="tank" value="-200" />			</attack>			<defense base="1300" hitPoints="10">
				<target type="unit" key="animal" value="-200" />				<target type="unit" key="ship" value="-100" />				<target type="unit" key="tank" value="-100" />			</defense>
			<movement cost="4" type="normal" level="air" />
		</battle>
	</resource>
	
	<resource type="Ship" value="NuclearFighter">
		<dependencies>
			<resource-ref type="Building" value="StarPort" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="250" />
			<resource-needed type="mp" value="300" />
			<resource-needed type="energy" value="200" />
			<resource-needed type="uranium" value="1" />
			<resource-ref type="Building" value="StarPort" />
			<duration value="30" quantity="100" />
		</cost>
		<attributes>
			<attribute type="TeletransportationCost" value="4"/>
		</attributes>
		<battle>			<attack base="150" range="1" maximumDamage="9" minimumDamage="5">				<target type="unit" key="animal" value="50" />				<target type="unit" key="ship" value="-20" />				<target type="unit" key="tank" value="-20" />			</attack>			<defense base="170" hitPoints="10">
				<target type="unit" key="animal" value="-20" />				<target type="unit" key="ship" value="-20" />				<target type="unit" key="tank" value="-20" />			</defense>
			<movement cost="1" type="all" level="air" />
		</battle>
	</resource>
	
</resources>

=== zi-yu/orionsbelt/tests/conf/resources/rare.xml
<?xml version="1.0" ?>
<!DOCTYPE resources SYSTEM "conf.dtd">
<resources>

	<!-- 
		Recursos Específicos de Planetas 
	-->
	
	<!-- Deserto -->
	<resource type="Rare" value="elk">
		<attributes>
			<attribute type="SpecificTerrain" value="1"/>
			<attribute type="DefaultRatio" value="50"/>
			<attribute type="Teletransportable" value="1"/>
			<attribute type="TeletransportationCost" value="20"/>
			<attribute type="MarketResource" value="1"/>
		</attributes>
	</resource>
	
	<!-- Água -->
	<resource type="Rare" value="hydrogen">
		<attributes>
			<attribute type="SpecificTerrain" value="0"/>
			<attribute type="DefaultRatio" value="50"/>
			<attribute type="Teletransportable" value="1"/>
			<attribute type="TeletransportationCost" value="20"/>
			<attribute type="MarketResource" value="1"/>
		</attributes>
	</resource>
	
	<!-- Floresta -->
	<resource type="Rare" value="plastic">
		<attributes>
			<attribute type="SpecificTerrain" value="4"/>
			<attribute type="DefaultRatio" value="50"/>
			<attribute type="Teletransportable" value="1"/>
			<attribute type="TeletransportationCost" value="20"/>
			<attribute type="MarketResource" value="1"/>
		</attributes>
	</resource>
	
	<!-- Rochoso -->
	<resource type="Rare" value="titanium">
		<attributes>
			<attribute type="SpecificTerrain" value="2"/>
			<attribute type="DefaultRatio" value="50"/>
			<attribute type="Teletransportable" value="1"/>
			<attribute type="TeletransportationCost" value="20"/>
			<attribute type="MarketResource" value="1"/>
		</attributes>
	</resource>
	
	<!-- Terrestre -->
	<resource type="Rare" value="oil">
		<attributes>
			<attribute type="SpecificTerrain" value="3"/>
			<attribute type="DefaultRatio" value="50"/>
			<attribute type="Teletransportable" value="1"/>
			<attribute type="TeletransportationCost" value="20"/>
			<attribute type="MarketResource" value="1"/>
		</attributes>
	</resource>
	
	<!-- Gêlo -->
	<resource type="Rare" value="diamond">
		<attributes>
			<attribute type="SpecificTerrain" value="5"/>
			<attribute type="DefaultRatio" value="50"/>
			<attribute type="Teletransportable" value="1"/>
			<attribute type="TeletransportationCost" value="20"/>
			<attribute type="MarketResource" value="1"/>
		</attributes>
	</resource>
	
	<!--
		Recursos Genéricos
	-->
	
	<resource type="Rare" value="silver">
		<attributes>
			<attribute type="SpecificTerrain" value="-1"/>
			<attribute type="DefaultRatio" value="50"/>
			<attribute type="Teletransportable" value="1"/>
			<attribute type="TeletransportationCost" value="20"/>
			<attribute type="MarketResource" value="1"/>
		</attributes>
	</resource>
	
	<resource type="Rare" value="uranium">
		<attributes>
			<attribute type="SpecificTerrain" value="-1"/>
			<attribute type="DefaultRatio" value="50"/>
			<attribute type="Teletransportable" value="1"/>
			<attribute type="TeletransportationCost" value="100"/>
			<attribute type="MarketResource" value="1"/>
		</attributes>
	</resource>
	
	<resource type="Rare" value="gas">
		<attributes>
			<attribute type="SpecificTerrain" value="-1"/>
			<attribute type="DefaultRatio" value="50"/>
			<attribute type="Teletransportable" value="1"/>
			<attribute type="TeletransportationCost" value="20"/>
			<attribute type="MarketResource" value="1"/>
		</attributes>
	</resource>
	
</resources>

=== zi-yu/orionsbelt/chronos/conf/resources/soldiers.xml
<?xml version="1.0" ?>
<!DOCTYPE resources SYSTEM "conf.dtd">
<resources>

	<resource type="Intrinsic" value="marine" category="soldier">
		<cost>
			<resource-needed type="gold" value="5" />
			<resource-needed type="mp" value="10" />
			<resource-needed type="energy" value="5" />
			<resource-needed type="labor" value="1" />
			<reserve-resource type="housing" value="1" />
			<resource-ref type="Building" value="Barracks" />
			<duration value="20" quantity="2000" />
		</cost>
		<attributes>
			<attribute type="Teletransportable" value="1"/>
			<attribute type="TeletransportationCost" value="9"/>
			<mod type="food" value="-2" />
		</attributes>
		<onCancelDuringBuild>
			<add type="Intrinsic" resource="labor" value="1" />
			<add type="Intrinsic" resource="housing" value="1" />
		</onCancelDuringBuild>
	</resource>
	
	<resource type="Intrinsic" value="spy" category="soldier">
		<cost>
			<resource-needed type="gold" value="10" />
			<resource-needed type="mp" value="15" />
			<resource-needed type="energy" value="10" />
			<resource-needed type="labor" value="1" />
			<reserve-resource type="housing" value="1" />
			<resource-ref type="Building" value="Barracks" />
			<resource-ref type="Research" value="Espionage" />
			<duration value="20" quantity="2400" />
		</cost>
		<attributes>
			<attribute type="Teletransportable" value="1"/>
			<attribute type="TeletransportationCost" value="6"/>
			<mod type="food" value="-2" />
		</attributes>
		<onCancelDuringBuild>
			<add type="Intrinsic" resource="labor" value="1" />
			<add type="Intrinsic" resource="housing" value="1" />
		</onCancelDuringBuild>
	</resource>
	
</resources>

=== zi-yu/orionsbelt/chronos/conf/resources/waterbuildings.xml
<?xml version="1.0" ?>
<!DOCTYPE resources SYSTEM "conf.dtd">
<resources>
	<resource type="Building" value="WaterSchool" category="general">
		<dependencies>
			<resource-ref type="Research" value="WaterExplorationI" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="100" />
			<resource-needed type="mp" value="800" />
			<resource-needed type="energy" value="10" />
			<resource-needed type="waterSpace" value="1" />
			<resource-available type="Intrinsic" resource="labor" value="100" />
			<duration value="10"/>
		</cost>
		<attributes>
			<mod type="culture" value="10"/>
		</attributes>
		<oncomplete>
			<add type="Intrinsic" resource="score" value="10" />
		</oncomplete>
		<onremove>
			<add type="Intrinsic" resource="mp" value="200" />
			<add type="Intrinsic" resource="waterSpace" value="1" />
			<add type="Intrinsic" resource="score" value="-10" />
		</onremove>
		<onCancelDuringBuild>
			<add type="Intrinsic" resource="waterSpace" value="1" />
		</onCancelDuringBuild>
		<keywords>
			<keyword key="waterSpace" />
			<keyword key="culture" />
			<keyword key="resourceGenerator" />
		</keywords>
	</resource>

	<resource type="Building" value="WaterUniversity" category="general">
		<dependencies>
			<resource-ref type="Research" value="WaterExplorationI" />
			<resource-ref type="Building" value="WaterSchool" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="100" />
			<resource-needed type="mp" value="1800" />
			<resource-needed type="energy" value="100" />
			<resource-needed type="waterSpace" value="3" />
			<resource-available type="Intrinsic" resource="labor" value="1000" />
			<duration value="20"/>
		</cost>
		<attributes>
			<mod type="culture" value="50"/>
		</attributes>
		<oncomplete>
			<add type="Intrinsic" resource="score" value="30" />
		</oncomplete>
		<onremove>
			<add type="Intrinsic" resource="mp" value="200" />
			<add type="Intrinsic" resource="waterSpace" value="3" />
			<add type="Intrinsic" resource="score" value="-30" />
		</onremove>
		<onCancelDuringBuild>
			<add type="Intrinsic" resource="waterSpace" value="3" />
			<add type="Intrinsic" resource="labor" value="900" />
		</onCancelDuringBuild>
		<keywords>
			<keyword key="waterSpace" />
			<keyword key="culture" />
			<keyword key="resourceGenerator" />
		</keywords>

	</resource>

	<resource type="Building" value="WaterResearchCampus" category="general">
		<dependencies>
			<resource-ref type="Research" value="WaterExplorationII" />
			<resource-ref type="Building" value="WaterUniversity" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="1000" />
			<resource-needed type="mp" value="2800" />
			<resource-needed type="energy" value="200" />
			<resource-needed type="waterSpace" value="3" />
			<resource-available type="Intrinsic" resource="labor" value="2700" />
			<duration value="30"/>
		</cost>
		<attributes>
			<mod type="culture" value="65"/>
		</attributes>
		<oncomplete>
			<add type="Intrinsic" resource="score" value="30" />
		</oncomplete>
		<onremove>
			<add type="Intrinsic" resource="mp" value="200" />
			<add type="Intrinsic" resource="waterSpace" value="3" />
			<add type="Intrinsic" resource="score" value="-30" />
		</onremove>
		<onCancelDuringBuild>
			<add type="Intrinsic" resource="waterSpace" value="3" />
		</onCancelDuringBuild>
		<keywords>
			<keyword key="waterSpace" />
			<keyword key="culture" />
			<keyword key="resourceGenerator" />
		</keywords>
	</resource>

	<resource type="Building" value="WaterReclamation" category="upgrade">
		<dependencies>
			<resource-ref type="Research" value="GeoPlanet" />
			<resource-ref type="Research" value="WaterExplorationII" />
			<resource-ref type="Building" value="WaterResearchCampus" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="600000" />
			<resource-needed type="mp" value="500000" />
			<resource-needed type="energy" value="904000" />
			<resource-available type="Intrinsic" resource="labor" value="4500" />
			<restriction resource="Building.WaterReclamation" type="equal-to" value="0" />
			<queueRestriction type="Building" value="WaterReclamation" />
			<duration value="650"/>
		</cost>
		<oncomplete>
			<add type="Intrinsic" resource="waterSpace" value="20" />
			<add type="Intrinsic" resource="score" value="4550" />
		</oncomplete>
		<onremove>
			<static evaluate="false" action="false" />
		</onremove>
		<keywords>
			<keyword key="waterSpace" />
		</keywords>
	</resource>

	<resource type="Building" value="Zoomarine" category="general">
		<dependencies>
			<resource-ref type="Research" value="WaterExplorationIII" />
			<resource-ref type="Research" value="Commerce" />
			<resource-ref type="Research" value="Geology" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="4800" />
			<resource-needed type="mp" value="4600" />
			<resource-needed type="energy" value="1104" />
			<resource-needed type="waterSpace" value="2" />
			<resource-available type="Intrinsic" resource="labor" value="5000" />
			<duration value="53"/>
		</cost>
		<attributes>
			<mod type="culture" value="25"/>
			<mod type="labor" value="10" />
			<mod type="gold" value="350" />
			<mod type="energy" value="-80" />
			<mod type="polution" value="80" />
		</attributes>
		<oncomplete>
			<add type="Intrinsic" resource="score" value="60" />
		</oncomplete>
		<onremove>
			<add type="Intrinsic" resource="mp" value="200" />
			<add type="Intrinsic" resource="waterSpace" value="2" />
			<add type="Intrinsic" resource="score" value="-60" />
		</onremove>
		<onCancelDuringBuild>
			<add type="Intrinsic" resource="waterSpace" value="2" />
		</onCancelDuringBuild>
		<keywords>
			<keyword key="waterSpace" />
			<keyword key="culture" />
			<keyword key="gold" />
			<keyword key="labor" />
			<keyword key="resourceGenerator" />
		</keywords>
	</resource>

	<resource type="Building" value="Spa" category="upgrade">
		<dependencies>
			<resource-ref type="Research" value="Medicine" />
			<resource-ref type="Research" value="WaterExplorationII" />
		</dependencies>
		<cost>
			<resource-needed type="gold" value="4400" />
			<resource-needed type="mp" value="3300" />
			<resource-needed type="energy" value="350" />
			<resource-needed type="waterSpace" value="2" />
			<resource-available type="Intrinsic" resource="labor" value="3000" />
			<restriction resource="Building.Spa" type="equal-to" value="0" />
			<queueRestriction type="Building" value="Spa" />
			<duration value="35"/>
		</cost>
		<attributes>
			<mod type="culture" value="40"/>
			<mod type="labor" value="15" />
		</attributes>
		<oncomplete>
			<addRatio type="labor" value="22" />
			<add type="Intrinsic" resource="score" value="330" />	
		</oncomplete>
		<onremove>
			<static evaluate="false" action="false" />
		</onremove>
		<onCancelDuringBuild>
			<add type="Intrinsic" resource="waterSpace" value="2" />
			<add type="Intrinsic" resource="labor" value="3000" />
		</onCancelDuringBuild>
		<keywords>
			<keyword key="waterSpace" />
			<keyword key="culture" />
			<keyword key="labor" />
			<keyword key="resourceGenerator" />
		</keywords>
	</resource>

</resources>
